<a href="https://colab.research.google.com/github/KissTK322/Newton-Method-2D-in-Modulo-Research/blob/main/newtonmethod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1D newton medthod OLD --> New Version

#1d newton method

In [ ]:
import math

def objective(x):
	return x**3 + 2

def derivative(x):
	return 3*x**2

def newton(x0 , e , mx) :
	xn = x0
	for n in range(0 , mx) :
		nfx = objective(xn)
		if abs(nfx) < e:
			return xn
		ndx = derivative(xn)
		xn = xn - (nfx/ndx)
		print(xn)

In [ ]:
ans = newton(-0.5 , 1e-10 , 10)
print(ans)

-3.0
-2.074074074074074
-1.5376905391786344
-1.3070762193875483
-1.2616018009550374
-1.2599232880572124
-1.2599210498988491
-1.2599210498988491


#1D newton method with mod


In [ ]:
def newton_mod(x0 , a , n , p) :
	i = 2
	cnt = 1
	xn = x0
	while (True) :
		xnn = xn * (2 - a * xn)
		if(abs(xnn) < (p ** i)) :
			xn = (p ** i) - abs(xnn)
			print("x" + str(cnt) + " is " + str(xn))
		else :
			k = math.ceil(abs(xnn) / (p ** i))
			xn = ((p ** i) * k) - abs(xnn)
			print("x" + str(cnt) + " is " + str(xn))
		if(i == n) : return xn
		i = i * 2
		cnt = cnt + 1

In [ ]:
ans = newton_mod(2 , 3 , 8 , 5)
print(str(ans) + " is congruence to 1 mod p^" + str(8))

x1 is 17
x2 is 417
x3 is 260417
260417 is congruence to 1 mod p^8


In [ ]:
ans = newton_mod(3 , 5 , 32 , 7)
print(str(ans) + " is congruence to 1 mod p^" + str(32))

x1 is 10
x2 is 1921
x3 is 4611841
x4 is 26586344455681
x5 is 883542139395136517044239361
883542139395136517044239361 is congruence to 1 mod p^32


#1D newton method with mod every testcase


In [ ]:
from random import randint , getrandbits
import math
def newton_mod(x0 , a , n , p) :
	i = 2
	cnt = 1
	xn = x0
	while (True) :
		xnn = xn * (2 - a * xn)
		if(abs(xnn) < (p ** i)) :
			xn = (p ** i) - abs(xnn)
			#print("x" + str(cnt) + " is " + str(xn))
		else :
			k = math.ceil(abs(xnn) / (p ** i))
			xn = ((p ** i) * k) - abs(xnn)
			#print("x" + str(cnt) + " is " + str(xn))
		if(i == n) : return xn
		i = i * 2
		cnt = cnt + 1

In [ ]:
for i in range(0 , 5) :
  x0 = randint(3 , 10)
  # a = randint(3 , 10)
  # n = randint(3 , 10)
  # p = randint(3 , 10)
  ans = newton_mod(x0 , 3 , 8 , 5)
  print("#Tasecase " + str(i) + " : (x0 = " + str(x0) + ") " + str(ans) + " is congruence to 1 mod p^" + str(8) + "\n")


x1 is 20
x2 is 90
x3 is 366505
#Tasecase 0 : (x0 = 10) 366505 is congruence to 1 mod p^8

x1 is 24
x2 is 195
x3 is 276940
#Tasecase 1 : (x0 = 8) 276940 is congruence to 1 mod p^8

x1 is 10
x2 is 345
x3 is 34240
#Tasecase 2 : (x0 = 5) 34240 is congruence to 1 mod p^8

x1 is 10
x2 is 345
x3 is 34240
#Tasecase 3 : (x0 = 4) 34240 is congruence to 1 mod p^8

x1 is 4
x2 is 585
x3 is 146370
#Tasecase 4 : (x0 = 6) 146370 is congruence to 1 mod p^8



In [ ]:
a = 4
n = 8
p = 13
for i in range(0 , p) :
  x0 = i
  ans = newton_mod(x0 , a , n , p)
  print("#Tasecase " + str(i) + " : (x0 = " + str(x0) + ") " + str(ans) + " is congruence to "  + str((ans * a) % (p ** n)) +  " mod p^" + str(n) + "\n")

#Tasecase 0 : (x0 = 0) 815274421 is congruence to 813905521 mod p^8

#Tasecase 1 : (x0 = 1) 779206829 is congruence to 669635153 mod p^8

#Tasecase 2 : (x0 = 2) 612351590 is congruence to 2214197 mod p^8

#Tasecase 3 : (x0 = 3) 514586759 is congruence to 426885594 mod p^8

#Tasecase 4 : (x0 = 4) 658391329 is congruence to 186373153 mod p^8

#Tasecase 5 : (x0 = 5) 759338131 is congruence to 590160361 mod p^8

#Tasecase 6 : (x0 = 6) 301881357 is congruence to 391794707 mod p^8

#Tasecase 7 : (x0 = 7) 446484090 is congruence to 154474918 mod p^8

#Tasecase 8 : (x0 = 8) 202356830 is congruence to 809427320 mod p^8

#Tasecase 9 : (x0 = 9) 40553857 is congruence to 162215428 mod p^8

#Tasecase 10 : (x0 = 10) 611798041 is congruence to 1 mod p^8

#Tasecase 11 : (x0 = 11) 757858861 is congruence to 584243281 mod p^8

#Tasecase 12 : (x0 = 12) 60527701 is congruence to 242110804 mod p^8



#2D newton medthod OLD --> New Version

#2D newton method

In [ ]:
def objective1(X, Y):
    return 3*X**2 + 2*Y**2 - 25

def objective2(X, Y):
    return 2*X**2 - Y - 15

In [ ]:
from numpy import matrix
import numpy as np
count = 1
for x in range(0,100):
    if count == 1:
        X = 1
        Y = 1

    f1 = objective1(X , Y)
    f2 = objective2(X , Y)

    if f1 == 0 and f2==0:
        break
    print("\r\nIteration=%d" %count)
    count += 1
    print("f1= %f" %(f1))
    print("f2= %f" %(f2))

    A = 6*X
    B = 4*Y
    C = 4*X
    D = -1

    print(A,B)
    print(C,D)
    J = np.matrix([[A,B],[C,D]]).I  #Jacobian matrix
    f3 = np.matrix([[f1],[f2]])
    T = np.matrix([[X],[Y]])
    Delta = J*f3
    E = T-Delta
    X = np.squeeze(np.asarray(E[0]))
    Y = np.squeeze(np.asarray(E[1]))
    print(J)
    print("X=%f, Y=%f" %(X,Y))


Iteration=1
f1= -20.000000
f2= -14.000000
6 4
4 -1
[[ 0.04545455  0.18181818]
 [ 0.18181818 -0.27272727]]
X=4.454545, Y=0.818182

Iteration=2
f1= 35.867769
f2= 23.867769
26.72727272727273 3.2727272727272707
17.81818181818182 -1
[[ 0.01175899  0.03848397]
 [ 0.20952381 -0.31428571]]
X=3.114250, Y=0.804329

Iteration=3
f1= 5.389556
f2= 3.592782
18.685502252849194 3.217316017316014
12.457001501899462 -1
[[ 0.01701733  0.05475014]
 [ 0.21198495 -0.31797742]]
X=2.825829, Y=0.804248

Iteration=4
f1= 0.249560
f2= 0.166374
16.954975131649544 3.2169905772548733
11.303316754433029 -1
[[ 0.01875552  0.06033633]
 [ 0.21199958 -0.31799936]]
X=2.811110, Y=0.804248

Iteration=5
f1= 0.000650
f2= 0.000433
16.86666110746272 3.216990566028298
11.244440738308478 -1
[[ 0.01885372  0.06065225]
 [ 0.21199958 -0.31799936]]
X=2.811072, Y=0.804248

Iteration=6
f1= 0.000000
f2= 0.000000
16.8664299008588 3.2169905660282994
11.244286600572535 -1
[[ 0.01885398  0.06065308]
 [ 0.21199958 -0.31799936]]
X=2.811072, Y

#Test 2d Newton Method in Mod (Version not proof)


In [ ]:
import numpy as np
from sympy import symbols, diff

# 2X + 3Y con 1 % p
# 5X + 4Y con 1 % p

def objective1(X, Y):
    return 1 + ((2 * Y) / X) - (1 / X)

def objective2(X, Y):
    return 4 + ((3 * Y) / X) - (1 / X)


In [1]:
from numpy import matrix
import numpy as np
count = 1
for i in range(0,100):
    if count == 1:
        X = 1
        Y = 1

    f1 = objective1(X , Y)
    f2 = objective2(X , Y)

    if f1 == 0 and f2==0:
        break
    print("\r\nIteration=%d" %count)
    count += 1
    print("f1= %f" %(f1))
    print("f2= %f" %(f2))

    A = -((2 * Y) / (X**2)) + (1 / (X**2))
    B = (2 / X)
    C = -((3 * Y) / (X**2)) + (1 / (X**2))
    D = (3 / X)

    print(A,B)
    print(C,D)
    J = np.matrix([[A,B],[C,D]]).I  #Jacobian matrix
    f3 = np.matrix([[f1],[f2]])
    T = np.matrix([[X],[Y]])
    Delta = J*f3
    E = T-Delta
    X = np.squeeze(np.asarray(E[0]))
    Y = np.squeeze(np.asarray(E[1]))
    print(J)
    print("X=%f, Y=%f" %(X,Y))

NameError: ignored

#2D newton method with mod

In [ ]:
import math

while(True):
  a, b, c, d = map(int, input("Enter coefficients a, b, c, d separated by spaces: ").split())
  fnd = 0
  if(a*d - b*c == 0) :
    print("ERROR")
    fnd = 1
  if(abs(d) - abs(b) != 1) :
    print("ERROR")
    fnd = 1
  if(fnd == 0) :
    p = int(input("Enter mod value as p:"))
    n = int(input("Enter number of p raise to the power of n as n : "))

    # เลือกให้ถูก

    X = ((((a*d - b*c) % p) ** (p-2)) * ((d % p) + (-b % p))) % p
    Y = ((((a*d - b*c) % p) ** (p-2)) * ((-c % p) + (a % p))) % p


    for i in range(int(math.log2(n))+1):
        print(X, Y, (a * X + b * Y) % (p ** (2 ** i)), (c * X + d * Y) % (p ** (2 ** i)))

        X1 = X * (2 + X * (c * b - a * d))
        Y1 = Y - X * (d * a * Y - b * c * Y + c - a)

        X = X1
        Y = Y1


4 9 1 1
56 113 1 1
9520 19041 1 1
271910240 543820481 1 1
221805536394393280 443611072788786561 1 1
147593087925613566101437730716261760 295186175851227132202875461432523521 1 1


#Debug Zone

#Partial Diff code

In [ ]:
from sympy import symbols, diff

X, Y = symbols('X Y', real=True)
f1 = 3*X**3 + 2*Y**3 - 25
partial_derivative = diff(f1, X)

print(partial_derivative)

partial_derivative_at_X_1 = partial_derivative.subs(X, 2)

print(partial_derivative_at_X_1)

numeric_value = partial_derivative_at_X_1.evalf()

print(numeric_value)


9*X**2
36
36.0000000000000


In [ ]:
from sympy import symbols, diff

X, Y = symbols('X Y', real=True)
f1 = 3*X**3 + 2*Y**3 - 25
partial_derivative = diff(f1, X)

print("Partial derivative:", partial_derivative)

partial_derivative_at_point = partial_derivative.subs({X: 1, Y: 1})

print("Partial derivative at (X = 1, Y = 1):", partial_derivative_at_point)


Partial derivative: 9*X**2
Partial derivative at (X = 1, Y = 1): 9


#Debuging


In [ ]:
# 2X + 3Y con 1 % 5
# 5X + 4Y con 1 % 5

# กำหนดมา
a= 2
b= 3
c= 5
d= 4

p = 5

# เลือกให้ถูก
X= 2
Y= 4

for i in range(0,10):
  print(X,Y, (a*X+b*Y) % p**(2**i) , (c*X+d*Y) % p**(2**i))

  X1 = X * (2+X*(c*b-a*d))
  #Y1 = Y * (2+X*(c*b-a*d))
  Y1 = Y-X*(d*a*Y - b*c*Y + c - a)
 # Y1 = -(Y**2)*(c*b-a*d) + 2 * Y * (d-b)

  X=X1
  Y=Y1


2 4 1 1
32 54 1 1
7232 12054 1 1
366127232 610212054 1 1
938344050816127232 1563906751360212054 1 1
6163426903914131357201508113316127232 10272378173190218928669180188860212054 1 1
265914818399247745066772943536528974303337743581973232461937836238316127232 443191363998746241777954905894214957172229572636622054103229727063860212054 1 1
494974834510134349644569885376085734657193895848350089733821666996021210767326732431066241237979212218270022706886493831949077762796410492488316127232 824958057516890582740949808960142891095323159747250149556369444993368684612211220718443735396632020363783371178144156386581796271327350820813860212054 1 1
1715000607588344204283924515026996851110946326828568213237450166667700779434195230232698599189971000362067917517959523213397262272353677827039363913258038733261183771833286274911747316925728925843240259788749654647185694136906562928782379157780453575647663613925172513116227232135965355804988316127232 2858334345980573673806540858378328085184910544714280355

In [ ]:

# โจทย์กำหนดมา
a=15
p=26

# เลือกให้ถูก
x=7

# ถ้าเลือกถูก จะได้ผลแบบนี้
for i in range(8):
  print(i,x, (a*x) % p**(2**i))
  x = x*(2-a*x)


0 7 1
1 -721 1
2 -7799057 1
3 -912379366936849 1
4 -12486541638181282077656044605713 1
5 -2338705831230523431986753460223834371223401241611462196572786961 1
6 -82043174475474803252883682755971510500414458308141032126903375117410977988386714598370146101197451557491623948540988613519806737 1
7 -100966237170198003867907387508795818419403800179969329378053819595151734751214629517443027514402327926368301660808264169848367111852694958080354111548981163165287015780732328244743005025565938283109961857827995479410967333626725511582620486465536314498421009 1


In [ ]:
import math
# 2X + 3Y con 1 % 5
# 5X + 4Y con 1 % 5

#ax + by con 1 % p
#cx + dy con 1 % p

# กำหนดมา
while(1):
  a, b, c, d = map(int, input("Enter coefficients a, b, c, d separated by spaces: ").split())
  if(a*d - b*c == 0) :
    print("Prap Kuy Lek Mak Mak @@!!@@")
    exit(0)

  p = int(input("Enter mod value as p:"))
  n = int(input("Enter number of p raise to the power of n as n : "))

  # เลือกให้ถูก

  X = ((((a*d - b*c) % p) ** (p-2)) * ((d % p) + (-b % p))) % p
  Y = ((((a*d - b*c) % p) ** (p-2)) * ((-c % p) + (a % p))) % p


  while(n != 0):
      print(X, Y, (a * X + b * Y) % (p ** (2 ** i)), (c * X + d * Y) % (p ** (2 ** i)))

      X1 = X * (2 + X * (c * b - a * d))
      Y1 = Y - X * (d * a * Y - b * c * Y + c - a)

      X = X1
      Y = Y1
      n = int(n/2)
      print(n)


Enter coefficients a, b, c, d separated by spaces: 20 38 11 37
Enter mod value as p:53
Enter number of p raise to the power of n as n : 8
13 42 1856 1697
4
-54392 -175653 50969609806960450804708578438661446876896848088102465187403574733292372956974338597354922088320561602090763197667068876167406351107657977136930844105302840794025918204276758650219696822469649803013656008586606773676131107 50969609806960450804708578438661446876896848088102465187403574733292372956974338597354922088320561602090763197667068876167406351107657977136930844105302840794025918204276758650219696822469649803013656008586606773676796288
2
-952633780592 -3076426653453 50969609806960450804708578438661446876896848088102465187403574733292372956974338597354922088320561602090763197667068876167406351107657977136930844105302840794025918204276758650219696822469649803013656008586470816795450707 509696098069604508047085784386614468768968480881024651874035747332923729569743385973549220883205616020907631976670688761674063511076

KeyboardInterrupt: ignored

In [ ]:
import math
# 2X + 3Y con 1 % 5
# 5X + 4Y con 1 % 5

#ax + by con 1 % p
#cx + dy con 1 % p

# กำหนดมา
while(1):
  a, b, c, d = map(int, input("Enter coefficients a, b, c, d separated by spaces: ").split())
  if(a*d - b*c == 0) :
    print("@@!!@@")
    exit(0)

  p = int(input("Enter mod value as p:"))

  # เลือกให้ถูก

  X = ((((a*d - b*c) % p) ** (p-2)) * ((d % p) + (-b % p))) % p
  Y = ((((a*d - b*c) % p) ** (p-2)) * ((-c % p) + (a % p))) % p


  for i in range(11):
      print(X, Y, (a * X + b * Y) % (p ** (2 ** i)), (c * X + d * Y) % (p ** (2 ** i)))

      X1 = X * (2 + X * (c * b - a * d))
      Y1 = Y - X * (d * a * Y - b * c * Y + c - a)

      X = X1
      Y = Y1


Enter coefficients a, b, c, d separated by spaces: 20 38 11 37
Enter mod value as p:53
13 42 1 1
-54392 -175653 1422 870
-952633780592 -3076426653453 4975041 6157423
-292218580615854093537850592 -943687961056933828951983453 60040321639977 38502620808486
-27496127032000502525453669481065120670034365750425350592 -88795736400833164069655040152113525891401303014814483453 611821546995639902892944640 452699391255044749665088013
-243443914566690622018117825787664051105943095332854607537298492733120396972988719355201613227475249434109800350592 -786175509048703406588975487579517240309873580268465954806831333163231102769400846376475460637832257133092939483453 5279457902802329816581883365598775955175540061833762516 2205964315171922737573973399338468988241499784157432240
-1908331053173644030036977754917645548330311147009715927045756652425667687420968655900962983871790502011997591429217519457096759098353733276974120470661226476575293137290208335695126592354957110735146152830950413998332082855035059

KeyboardInterrupt: ignored

In [ ]:
import math

x = int(input("Enter an integer: "))  # Prompt the user for an integer input
y = math.log2(x)
print(y)


Enter an integer: 8
3.0


In [ ]:
a, b, c, d = map(int, input("Enter coefficients a, b, c, d separated by spaces: ").split())

p = int(input("Enter mod value as p:"))

# เลือกให้ถูก

X = ((((a*d - b*c) % p) ** (p-2)) * ((d % p) + (-b % p))) % p
Y = ((((a*d - b*c) % p) ** (p-2)) * ((-c % p) + (a % p))) % p


Enter coefficients a, b, c, d separated by spaces: 2 3 5 4
Enter mod value as p:5


(2, 4)